# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Development

on:
  push:
    branches: ['final2024']
  pull_request:
    branches: ['final2024']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - name: 'âœ¨ checkout code'
        uses: actions/checkout@v4

      - name: 'ğŸ”§ setup node.js'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: 'âš’ï¸ Install dependencies'
        run: npm ci
      - name: 'ğŸš€ Run tests'
        run: npm test
